yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'


urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='edit'),
    path('posts/<int:post_id>/comment/', views.add_comment, name='add_comment')
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
]
handler404 = 'core.views.page_not_found'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField(max_length=300)

    def __str__(self):
        return self.title


class Post(models.Model):
    MAX_LENGTH_TEXT = 15
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        verbose_name='Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        related_name='posts',
        on_delete=models.SET_NULL,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        verbose_name='Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text[:self.MAX_LENGTH_TEXT]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        related_name='comments',
        on_delete=models.CASCADE
    )
    author = models.ForeignKey(
        User,
        related_name='comments',
        on_delete=models.CASCADE
    )
    text = models.TextField('Текст', help_text='Текст нового комментария')
    created = models.DateTimeField(
        auto_now_add=True
    )

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = {
            'text': 'Текст поста',
            'group': 'Группы',
            'image': 'Картинка',
        }
        widgets = {
            'text': forms.Textarea(attrs={'class': 'card'}),
            'group': forms.Select(attrs={'class': 'card'}),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment

        fields = {
            'text': 'Текст комментария'
        }

yatube/posts/views.py
from django.views.decorators.cache import cache_page
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Post, Group, User, Comment
from .forms import PostForm, CommentForm
from .ulits import get_paginated_post


@cache_page(20 * 1, key_prefix='index_page')
def index(request):
    post_list = Post.objects.order_by('-pub_date')
    page_obj = get_paginated_post(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    template = 'posts/index.html'
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).order_by('-pub_date')
    page_obj = get_paginated_post(request, posts)
    context = {
        'page_obj': page_obj,
        'group': group
    }
    template = 'posts/group_list.html'
    return render(request, template, context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = Post.objects.filter(author=author).order_by('-pub_date')
    posts_other = Post.objects.exclude(author=author)
    page_obj = get_paginated_post(request, posts)
    context = {
        'page_obj': page_obj,
        'posts_other': posts_other,
        'author': author,
    }
    template = 'posts/profile.html'
    return render(request, template, context)


def post_detail(request, post_id):
    post = Post.objects.get(id=post_id)
    form = CommentForm(request.POST or None)
    comments = Comment.objects.filter(post_id=post_id).order_by('-created')
    context = {
        'post': post,
        'form': form,
        'comments': comments
    }
    template = 'posts/post_detail.html'
    return render(request, template, context)


@login_required
def post_create(request):
    user = request.user
    main = 'Создать пост от имени'
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=user.username)

    context = {
        'main': main,
        'user': user,
        'is_edit': False,
        'form': form
    }
    template = 'posts/create_post.html'
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    main = 'Редактировать пост'
    if request.user.id != post.author_id:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)

    context = {
        'main': main,
        'form': form,
        'is_edit': True,
    }
    template = 'posts/create_post.html'
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    post = Post.objects.get(id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {{ main }} {{ user.get_full_name }}
{% endblock %}
{% block content %}
    <style>
        .myfield{
            border:1px solid #ccc;
            border-radius:5px;
            height:25px;
            width:200px;
            margin: 10px 10px 10px 0;
        }
    </style>
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                {% if is_edit %}
                  Редактировать пост
                {% else %}
                  Новый пост
                {% endif %}
              </div>
              <div class="card-body">
               <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group row my-3 p-3">
                      <label for="field.id_for_label">
                        {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger" >*</span>
                      {% endif %}
                      </label>
                      {{ field }}
                        {% if field.help_text %}
                          <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                            {{ field.help_text|safe }}
                          </small>
                        {% endif %}
                    </div>
                    {% endfor %}

                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %}
                      {% csrf_token %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
{% load thumbnail %}
  Записи сообщества: {{ group.title }} - {{ group.description }}
{% endblock %}
{% block content %}
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
  {% for post in page_obj %}
  <ul>
  <li>
    Автор: {{ post.author.get_full_name }} <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a><br>
  </li>
  <li>
    Дата публикации: {{ post.pub_date|date:"d E Y" }}
  </li>
  </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
  <p>{{ post }}</p>
  <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a><br>
  {% if post.group %}
  <a href="{% url 'posts:group' post.group.slug %}">все записи группы</a>
  {% endif %}<br>
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
  <a href="{% url 'posts:index' %}">Вернуться на главную страницу</a>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
{% load thumbnail %}
  <h1>Последние обновления на сайте</h1>
  {% for post in page_obj %}
    <ul>
      <li>Автор: {{ post.author.get_full_name }} <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a><br></li>
      <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
    </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
    <p>{{ post }}</p>
    <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a><br>
    {% if user == post.author %}
    <a href="{% url 'posts:edit' post.id %}">редактировать пост</a><br>
    {% endif %}
    {% if post.group %}
      <a href="{% url 'posts:group' post.group.slug %}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %} 

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}{{ post }}{% endblock %}
{% block content %}
{% load thumbnail %}
  <main>
    <div class="row">
      <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
      {% if post.group %}
      <li class="list-group-item">
        Группа: {{ post.group }}<br>
        <a href="{% url 'posts:group' post.group.slug %}">все записи группы</a>
          {% endif %}
        </a>
      </li>
      <li class="list-group-item">
        Автор: {{ post.author.first_name }} {{ post.author.last_name }}
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <span >Всего постов автора: {{ post.author.posts.count }} </span>
      </li>
      <li class="list-group-item">
        <a href="{% url 'posts:profile' post.author.username %}">
          все посты пользователя
        </a>
      </li>
      </ul>
      </aside>
      <article class="col-12 col-md-9">
         {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{ post.text }}</p>
        {% if user == post.author %}
          <a class="btn btn-primary" href="{% url 'posts:edit' post.id %}">редактировать пост</a>
        <p align="right">Дата публикации: {{ post.pub_date|date:"d E Y" }}</p>
        {% endif %}
        <!-- Форма добавления комментария -->
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="card-header">
      <h5 class="card-header">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.get_full_name }}
        </a>
      </h5>
      <p>
        {{ comment.text }}
      </p>
      <p align="right">
        {{ comment.created }}
      </p>
    </div>
  </div>
{% endfor %}
      </article>
    </div>

  </main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}Профайл пользователя {{ author.get_full_name }} {% endblock %}
{% block content %}
{% load thumbnail %}
  <div class="container py-5">
  <h1>Все посты пользователя {{ author.first_name }} {{ author.last_name }}</h1>
  <h3>Всего постов: {{ author.posts.count }}</h3>
  <article>
  <p>
    {% for post in page_obj %}
      <li>Автор: {{ author.get_full_name }}</li>
      <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li><br>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
      {{ post }}
  </p>
      <a href="{% url 'posts:post_detail' post.id %}">читать</a><br>
      {% if user == post.author %}
        <a href="{% url 'posts:edit' post.id %}">редактировать пост</a><br>
      {% endif %}
      {% if post.group %}
      <a href="{% url 'posts:group' post.group.slug %}">все записи группы</a>
      {% endif %}<br>
      <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
    <hr>
    {% endfor %}
  </article>
  {% include 'posts/includes/paginator.html' %}
  </div>

<h1>Остальные посты</h1><br>
  {% for post in posts_other %}
    <p><li>Автор: {{ post.author.get_full_name }}
      </li>
      <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li><br>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      {{ post }}
    </p>
      {% if post.group %}
    <a href="{% url 'posts:group' post.group.slug %}">все записи группы</a>
    {% endif %}<br>
    <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
    <hr>
    <br>
  {% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endblock %}